petConnect/urls.py
from django.urls import path

from . import views

app_name = 'petConnect'
urlpatterns = [
    path('', views.inicial, name="home"),

]

petconnect/urls.py
from django.views.generic import TemplateView
from django.urls import path
from . import views


app_name = 'petconnect'
urlpatterns = [
    path('', TemplateView.as_view(
        template_name='petconnect/index.html'), name='index'),
    path('contato/', TemplateView.as_view(template_name='petconnect/contato.html'), name='contato'),
    path('sobre/', TemplateView.as_view(template_name='petconnect/sobre.html'), name='sobre'),
    path('promocoes/', TemplateView.as_view(template_name='petconnect/promocoes.html'), name='promocoes'),

    path('login/', views.logar, name='login'),
    path('logout/', views.deslogar, name='logout'),
    path('cadastro/', views.cadastro, name='cadastro'),
    path('perfil_usuario/', views.perfil_usuario, name='perfil_usuario'),
    path('cadastro_animal/', views.cadastro_animal, name='cadastro_animal'),
    path('consultas/agendadas', views.consultas_agendadas,
         name='consultas_agendadas'),
    path('consultas/anteriores', views.consultas_anteriores,
         name='consultas_anteriores'),
    path('consultas/pendentes', views.consultas_pendentes,
         name='consultas_pendentes'),
    path('agendar/', views.agendar_consulta, name='agendar_consulta'),
    path('servicos/', views.servicos, name='servicos'),
    path('animais_cadastrados/', views.animais_cadastrados,
         name='animais_cadastrados'),
    path('consultas_agendadas/', views.consultas_agendadas_dono,
         name='consultas_agendadas_dono'),
]

setup/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include("petconnect.urls"), name='petconnect'),
    path('admin/', admin.site.urls),
]

petConnect/models.py
from django.db import models

# Create your models here.

petconnect/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import CustomUserManager


class Usuario(AbstractUser):
    username = models.CharField(max_length=100, unique=False, blank=True, null=True)
    email = models.EmailField(max_length=100, unique=True)
    endereco = models.CharField(max_length=100, blank=True, null=True)
    telefone = models.CharField(max_length=20)
    is_dono = models.BooleanField(default=False)
    image = models.ImageField(upload_to='usuario_image', default='usuario_image/default.png', blank=True, null=True)
    data_nascimento = models.DateField(null=True, blank=True)
    cpf = models.CharField(max_length=20, null=True, blank=True)
    biografia = models.TextField(max_length=500, blank=True, null=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['first_name', 'last_name', 'cpf', 'telefone']

    objects = CustomUserManager()

    def __str__(self):
        return self.email


class Animais(models.Model):
    dono = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    nome = models.CharField(max_length=100)
    idade = models.IntegerField()
    especie = models.CharField(max_length=100, default='Desconhecido')
    raca = models.CharField(max_length=100)
    sexo = models.CharField(max_length=100, default='Desconhecido')
    image = models.ImageField(upload_to='animais_image', blank=True, null=True)

    def __str__(self):
        return self.nome
    

class Loja(models.Model):
    nome = models.CharField(max_length=100)
    endereco = models.CharField(max_length=100)
    telefone = models.CharField(max_length=20)
    cnpj = models.CharField(max_length=20)
    email = models.CharField(max_length=100)
    disponvel = models.BooleanField(default=True)
    image = models.ImageField(upload_to='pet_image', blank=True, default='pet_image/default.png')

    def __str__(self):
        return self.nome
    
    
class Promocoes(models.Model):
    cod = models.CharField(max_length=100)
    descricao = models.CharField(max_length=500)
    duracao = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField(default=False)
    porcentagem = models.FloatField()

    def __str__(self):
        return self.cod


class Servico(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.CharField(max_length=500)
    preco = models.FloatField()
    loja = models.ForeignKey(Loja, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome


class Agendamento(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    servico = models.ForeignKey(Servico, on_delete=models.CASCADE)
    animal = models.ForeignKey(Animais, on_delete=models.CASCADE)
    data_agendamento = models.DateTimeField(auto_now_add=True)
    data_consulta = models.DateTimeField()
    status = models.BooleanField(default=False)
    descricao = models.TextField(max_length=500)

    def __str__(self):
        return f'{self.usuario.email}: {self.data_agendamento}'

petconnect/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import Usuario


class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = Usuario
        fields = ('first_name', 'last_name', 'email', 'cpf', 'telefone')


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = Usuario
        fields = ('first_name', 'last_name', 'email', 'cpf', 'telefone')

petConnect/views.py
from django.shortcuts import render


# Create your views here.
def inicial(request):
    return render(request, 'petConnect/pages/index.html')

petconnect/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
import json
from .models import Usuario, Animais, Servico, Agendamento



def logar(request):
    if request.method == 'POST':
        email = request.POST['email']
        senha = request.POST['senha']
        user = authenticate(request, email=email, password=senha)
        if user is not None:
            login(request, user)
            return render(request, 'petconnect/index.html')
        else:
            context = {'error': 'Email não cadastrado'}
            return render(request, 'petconnect/login.html', context)
    return render(request, 'petconnect/login.html')


def deslogar(request):
    logout(request)
    return redirect('petconnect:index')


def cadastro(request):
    context = {}
    if request.method == 'POST':
        first_name = request.POST['nome']
        last_name = request.POST['sobrenome']
        email = request.POST['email']
        cpf = request.POST['cpf']
        telefone = request.POST['telefone']
        senha1 = request.POST['senha1']
        senha2 = request.POST['senha2']
        if senha1 == senha2:
            if Usuario.objects.filter(email=email).exists():
                context['error'] = 'Email já cadastrado'
            else:
                user = Usuario.objects.create_user(
                    first_name=first_name, last_name=last_name, email=email, cpf=cpf, telefone=telefone, password=senha1)
                user.save()
                return render(request, 'petconnect/index.html')
        else:
            context['error'] = 'Senhas não conferem'
    return render(request, 'petconnect/cadastro.html', context)


@login_required(login_url='petconnect:login')
def perfil_usuario(request):
    if request.user.is_dono:
        return render(request, 'petconnect/perfil_petshop.html')
    return render(request, 'petconnect/perfil_usuario.html')


@login_required(login_url='petconnect:login')
def cadastro_animal(request):
    if request.method == 'POST':
        nome = request.POST['nome']
        idade = request.POST['idade']
        especie = request.POST['especie']
        raca = request.POST['raca']
        sexo = request.POST['sexo']
        animal = Animais.objects.create(
            dono=request.user, nome=nome, idade=idade, especie=especie, raca=raca, sexo=sexo)
        animal.save()
        return redirect('petconnect:perfil_usuario')
    return render(request, 'petconnect/cadastro_animal.html')


@login_required(login_url='petconnect:login')
def consultas_agendadas(request):
    context = {}
    agendamentos = Agendamento.objects.filter(
        usuario=request.user, status=False)
    context['agendamentos'] = agendamentos
    return render(request, 'petconnect/agendamento/agendadas.html', context)


@login_required(login_url='petconnect:login')
def consultas_anteriores(request):
    context = {}
    agendamentos = Agendamento.objects.filter(
        usuario=request.user, status=True)
    context['agendamentos'] = agendamentos
    return render(request, 'petconnect/agendamento/anteriores.html', context)


@login_required(login_url='petconnect:login')
def consultas_pendentes(request):
    return render(request, 'petconnect/agendamento/pendentes.html')


@login_required(login_url='petconnect:login')
def agendar_consulta(request):
    context = {}
    if request.method == 'POST':
        servico_id = request.POST.get('servico', None)
        animal_id = request.POST.get('animal', None)
        data_consulta = request.POST.get('datahorario', None)
        servico = Servico.objects.get(id=servico_id)
        animal = Animais.objects.get(id=animal_id)
        if animal and servico and data_consulta:
            Agendamento.objects.create(
                usuario=request.user, servico=servico, animal=animal, data_consulta=data_consulta)
        return redirect('petconnect:consultas_agendadas')
    else:
        servicos = Servico.objects.all()
        animais = Animais.objects.filter(dono=request.user)
        context['servicos'] = servicos
        context['animais'] = animais
        return render(request, 'petconnect/agendamento/agendar.html', context)


@login_required(login_url='petconnect:login')
def animais_cadastrados(request):
    animais = Animais.objects.filter(dono=request.user)
    context = {'animais': animais}
    return render(request, 'petconnect/animais_cadastrados.html', context)


def servicos(request):
    servicos = Servico.objects.all()
    context = {'servicos': servicos}
    return render(request, 'petconnect/servicos.html', context)


def consultas_agendadas_dono(request):
    agendamentos = Agendamento.objects.all()
    context = {'agendamentos': agendamentos}
    return render(request, 'petconnect/consultas_agendadas.html', context)

templates/petconnect/animais_cadastrados.html
{% extends 'petconnect/perfil_usuario.html' %}

{% load static %}

{% block content_perfil %}
<section>
    {% for animal in animais %}
    <div class="animais-card">
        <div class="circulo2"></div>
        <h2>{{ animal.nome }}</h2>
        <h3>{{ animal.raca }}, {{ animal.idade }}</h3>
        <button>Ver Mais</button>
    </div>
    {% endfor %}

    <h4 id="animais-cadastro">Deseja cadastrar algum pet? <a href="{% url 'petconnect:cadastro_animal' %}">Clique aqui!</a></h4>
</section>
{% endblock %}

templates/petconnect/avaliacoes.html
{% extends 'petconnect/perfil_petshop.html' %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/perfil_petshop.css' %}">
<link rel="stylesheet" href="{% static 'css/avaliacoes.css' %}" />
{% endblock %}

{% block content_perfil %}
<section>
  <div class="consulta">
    <h4 class="agendamento-data">Data promoção: 20/10/2023</h4>
    <div class="info-consulta">
      <h5>Informações da promoção</h5>
      <p>Data Inicio: 22/10/2023</p>
      <p>Data Fim: 25/10/2023</p>
      <p>Tipo de serviço:</p>
      <p>Valor: 30%</p>
    </div>

    <button class="botao-card2">Excluir Promoção</button>
  </div>

  <div class="consulta">
    <h4 class="agendamento-data">Data promoção: 20/10/2023</h4>
    <div class="info-consulta">
      <h5>Informações da promoção</h5>
      <p>Data Inicio: 22/10/2023</p>
      <p>Data Fim: 25/10/2023</p>
      <p>Tipo de serviço:</p>
      <p>Valor: 30%</p>
    </div>

    <button class="botao-card2">Excluir Promoção</button>
  </div>

  <div class="consulta">
    <h4 class="agendamento-data">Data promoção: 20/10/2023</h4>
    <div class="info-consulta">
      <h5>Informações da promoção</h5>
      <p>Data Inicio: 22/10/2023</p>
      <p>Data Fim: 25/10/2023</p>
      <p>Tipo de serviço:</p>
      <p>Valor: 30%</p>
    </div>

    <button class="botao-card2">Excluir Promoção</button>
  </div>

  <div class="consulta">
    <h4 class="agendamento-data">Data promoção: 20/10/2023</h4>
    <div class="info-consulta">
      <h5>Informações da promoção</h5>
      <p>Data Inicio: 22/10/2023</p>
      <p>Data Fim: 25/10/2023</p>
      <p>Tipo de serviço:</p>
      <p>Valor: 30%</p>
    </div>

    <button class="botao-card2">Excluir Promoção</button>
  </div>
</section>
{% endblock %}

templates/petconnect/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="shortcut icon"
      href="{% static 'img/casa.png' %}"
      type="image/x-icon"
    />
    <title>PetConnect</title>
    <link rel="stylesheet" href="{% static 'css/index.css' %}" />
    {% block style %} {% endblock %}
  </head>
  <body>
    {% block header %}
    <header>
      <h1>
        Bem Vindo {% if user.is_authenticated %}{{ user.first_name }}{% else %}Visitante{% endif %}
      </h1>
      <a href="{% url 'petconnect:index' %}"
        ><img src="{% static 'img/logo.png' %}" alt="Logo do PetConnect"
      /></a>
      <div class="header__auth-area">
        <button>
          <a href="{% url 'petconnect:login' %}">Área Logada</a>
          <div id="triangulo-para-baixo"></div>
          <ul class="header__dropbox">
            {% if user.is_authenticated %}
            <li>
              <img src="{% static 'img/profile_user1.png' %}" alt="" /><a
                href="{% url 'petconnect:perfil_usuario' %}"
                >Perfil</a
              >
            </li>
            <li><a href="{% url 'petconnect:logout' %}">Sair</a></li>
            {% else %}
            <li><a href="{% url 'petconnect:login' %}">Login</a></li>
            <li><a href="{% url 'petconnect:cadastro' %}">Cadastro</a></li>
            {% endif %}
          </ul>
        </button>
      </div>
    </header>
    {% endblock %} {% block nav %}
    <nav>
      <ul>
        <li>
          <img src="{% static 'img/interrogacao.png' %}" alt="" /><a
            href="{% url 'petconnect:sobre' %}"
            >SOBRE NÓS</a
          >
        </li>
        <li>
          <img src="{% static 'img/medal.png' %}" alt="" /><a
            href="{% url 'petconnect:servicos' %}"
            >SERVIÇOS</a
          >
        </li>
        <li>
          <img src="{% static 'img/phone_call.png' %}" alt="" /><a
            href="{% url 'petconnect:contato' %}"
            >CONTATO</a
          >
        </li>
      </ul>
    </nav>
    {% endblock %} {% block content %}{% endblock %} {% block footer %}
    <footer>
      <section>
        <h3>Como podemos ajudar?</h3>
        <p>
          Conheça mais sobre nossa empresa, políticas e tenha o melhor
          atendimento do mercado pet 😍
        </p>
      </section>

      <div>
        <h3>Atendimento</h3>
        <ul>
          <li>Central de Atendimento</li>
        </ul>
      </div>
      <div>
        <h3>Institucional</h3>
        <ul>
          <li>Empresa</li>
          <li>Termos e condições de uso</li>
        </ul>
      </div>
      <div>
        <h3>Políticas</h3>
        <ul>
          <li>Aviso de privacidade</li>
          <li>Politica de cookies</li>
          <li>Politica de white hat</li>
          <li>Politica de cancelamento</li>
        </ul>
      </div>
    </footer>
    <div id="section2">
      <div>
        <h3>Onde Estamos</h3>
        <img src="{% static 'img/facebook.png' %}" alt="" />
        <img src="{% static 'img/instagram.png' %}" alt="" />
        <img src="{% static 'img/twitter.png' %}" alt="" />
        <img src="{% static 'img/youtube.png' %}" alt="" />
      </div>
      <div>
        <h3>Baixe o App</h3>
        <img src="{% static 'img/google_apple.png' %}" alt="" />
      </div>
    </div>
    <section id="the-end"><p>© PetConnect - 2024</p></section>
    {% endblock %}
  </body>
</html>

templates/petconnect/cadastro.html
{% extends 'petconnect/base.html' %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/cadastro.css' %}">
{% endblock %}

{% block content %}
<main>
  <h1>Crie sua conta!</h1>
  <div id="formulario">
    <form action="{% url 'petconnect:cadastro' %}" method="post">
      {% csrf_token %}
      <input type="text" name="nome" placeholder="Nome">
      <input type="text" name="sobrenome" placeholder="Sobrenome">
      <input type="e-mail" name="email" placeholder="E-mail">
      <input type="text" name="cpf" placeholder="CPF">
      <input type="text" name="telefone" placeholder="Telefone">
      <input type="password" name="senha1" placeholder="Senha">
      <input type="password" name="senha2" placeholder="Confirmar Senha">
      <input type="submit" name="enviar" value="Concluir" class="botao">
    </form>
  </div>
  {% if error %}
  <div class="mensagem">
    <p>{{ error }}</p>
  </div>
  {% endif %}
</main>
{% endblock %}

templates/petconnect/cadastro_animal.html
{% extends 'petconnect/base.html' %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/cadastro_animal.css' %}">
{% endblock %}

{% block content %}
<main>
    <h1>Cadastre seu Pet!</h1>
    <div id="formulario">
        <form action="{% url 'petconnect:cadastro_animal' %}" method="post">
            {% csrf_token %}
            <div class="forms">
              <label>Nome do Pet</label>
              <input type="text" name="nome">
              <label>Idade</label>
              <input type="text" name="idade">
            </div>
            <div class="forms">
              <label>Espécie</label>
              <select name="especie">
                  <option value="gato">Gato</option>
                  <option value="cachorro" selected>Cachorro</option>
                  <option value="cavalo">Cavalo</option>
              </select>
              <label>Raça</label>
              <input type="text" name="raca">
            </div>
            <fieldset>
                <legend>Gênero:</legend>

                <div>
                  <input type="radio" id="F" name="sexo" value="F" checked />
                  <label for="F">Fêmea</label>
                </div>

                <div>
                  <input type="radio" id="M" name="sexo" value="M" />
                  <label for="M">Macho</label>
                </div>
            </fieldset>
            <div class="forms" id="observacoes">
              <label>Observações</label>
              <input type="text" name="obs">
            </div>

            <div class="termos">
                <input
                  type="checkbox"
                  id="subscribeNews"
                  name="subscribe"
                  value="newsletter" />
                <label for="subscribeNews">Concordo com os <a href="#">Termos de Uso</a></label>
            </div>

            <div class="botoes">
              <a href="#"><input type="button" value="Voltar" class="botao" id="botao1"></a>
              <input type="submit" name="enviar" value="Concluir" class="botao">
            </div>
        </form>
    </div>
</main>
{% endblock %}

templates/petconnect/consultas_agendadas.html
{% extends 'petconnect/perfil_petshop.html' %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/perfil_petshop.css' %}" />
<link rel="stylesheet" href="{% static 'css/perfil_usuario.css' %}">
{% endblock %}

{% block content_perfil %}
<section>
    <div class="consulta-agendada">
        {% if agendamentos %}
        {% for agendamento in agendamentos %}
        <div class="consulta">
            <h3>{{ agendamento.data_agendamento }}</h3>
            <h3>{{ agendamento.data_consulta }}</h3>
            <h4>{{ agendamento.servico }}</h4>
            <h4>{{ agendamento.animal }}</h4>
            <h4>{{ agendamento.descricao }}</h4>
        </div>
        {% endfor %}
        {% else %}
        <h3>Você não possui consultas agendadas.</h3>
        <h4>Conheça nossos serviços <a href="/src/servicos.html">clicando aqui!</a></h4>
        {% endif %}
    </div>
</section>
{% endblock %}

templates/petconnect/contato.html
{% extends 'petconnect/base.html' %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/contato.css' %}">
{% endblock %}

{% block content %}
<section id="Banner1">
    <div class="banner">
        <div>
            <h1>Entre em contato com a gente</h1>
            <p>Estamos aqui para ajudar e responder a todas as suas perguntas relacionadas aos nossos produtos, serviços e cuidados com animais de estimação.</p>
            <button>SAIBA MAIS</button>
        </div>
        <div><img src="{% static 'img/cachorro_gato.png' %}" alt="" id="img-banner1"></div>
    </div>
</section>

<div id="Banner2">
    <div>
        <h2>Informações de Contato</h2>
        <p>
            Telefone: <b>[Inserir número de telefone]</b> <br>
            E-mail: <b>[Inserir endereço de e-mail]</b> <br>
            Endereço da Loja: <b>[Inserir endereço físico, se aplicável]</b> <br>
        </p>
    </div>

    <div>
        <h2>Horário de Funcionamento</h2>
        <p>
            Segunda a Sexta: <b>[Inserir horário de abertura e fechamento]</b> <br>
            Sábado e Domingo: <b>[Inserir horário de abertura e fechamento]</b>
        </p>
    </div>
</div>

<section id="como-chegar">
    <img src="{% static 'img/pawprint.png' %}" alt=""> <h1>COMO CHEGAR?</h1>

    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3959.4099527965836!2d-41.47228713100084!3d-7.0783794537172895!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x79c113670c147b5%3A0x80dce5eb74375e04!2sEspa%C3%A7o%20Pet!5e0!3m2!1sen!2sbr!4v1702057313345!5m2!1sen!2sbr" width="800" height="600" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>

</section>

<h2 id="titulo">Nos mande uma mensagem</h2>
<section id="mandar-mensagem">
    <div id="mandar-mensagem2">
        <div>
            <label for="username">Nome Completo <abbr title="required"></abbr></label>
            <input id="username" type="text" name="username" placeholder="Seu nome completo">
        </div>
        <div>
            <label for="email">Email <abbr title="required"></abbr></label>
            <input id="email" type="email" name="email" placeholder="Email para contato">
        </div>
        <div>
            <label for="mensagem">Mensagem<img src="#" alt=""> <abbr title="required"></abbr></label>
            <input id="mensagem" type="text" name="mensagem">
        </div>
        <input id="botao" type="button" value="ENVIAR">
    </div>
</section>

<section id="mais-duvidas">
    <div>
        <img src="#" alt="">
        <h2>Para mais informações, acesse a nossa seção de contato.</h2>
        <button>contato</button>
    </div>
</section>
{% endblock %}

templates/petconnect/login.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>PetConnect</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
    <div id="conteiner1" class="conteiner">
        <div id="conteiner-casa">    
            <svg xmlns="http://www.w3.org/2000/svg" width="833" height="1024" viewBox="0 0 833 1024" fill="none">
                <path d="M0 0H833L487.074 510L833 1024H0V0Z" fill="#8600C6"/>
            </svg>
        </div>
        <div id="casa"><img src="{% static 'img/casa.png' %}" alt=""></div>
    </div>


    <div id="conteiner2" class="conteiner">
        <div id="conteiner-child">
            <h2>USER LOGIN</h2>
            <form action="{% url 'petconnect:login' %}" method="post">
                {% csrf_token %}
                <div class="formulario-input">
                    <input id="username" type="text" name="email" placeholder="    Insira seu E-mail">
                </div>
                <div class="formulario-input">
                    <input id="senha" type="password" name="senha" placeholder="    Insira sua senha">
                    <p><a href="#">Esqueceu a senha?</a></p>
                </div>
                <input type="submit" value="ENTRAR" id="botao">
            </form>
            <p id="nao-possui">Não possui uma conta? <a href="#">Clique aqui!</a></p>

            <div id="linha-conteiner">
                <div class="linha"></div><p>OU</p><div class="linha"></div>
            </div>

            <div id="redes-sociais">
                <img src="{% static 'img/twitter.png' %}" alt="">
                <img src="{% static 'img/facebook.png' %}" alt="">
                <img src="{% static 'img/instagram.png' %}" alt="">
            </div>
        </div>
    </div>
</body>
</html>

templates/petconnect/perfil_petshop.html
{% extends 'petconnect/base.html' %}

{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'css/perfil_petshop.css' %}" />
{% endblock %}

{% block content %}
<div class="header-total">
  <div class="header">
    <div id="foto-perfil">
      <img src="{% static 'img/sample_profile.jpg' %}" alt="foto-perfil" />
    </div>
    <h4>Nome PetShop</h4>
    <h6>Picos, Piauí - Endereço</h6>

    <p id="paragrafo">
      Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce eget
      ullamcorper ex. Vestibulum ac ligula nec odio rhoncus consequat. Vivamus
      id condimentum nisl. Aenean congue diam id augue consequat, a pellentesque
      turpis aliquam. Vestibulum efficitur ullamcorper enim, congue mollis massa
      convallis non.
    </p>

    <div id="linha-horizontal"></div>
    <ul>
      <li><a href="{% url 'petconnect:consultas_agendadas' %}"> Consultas Pendentes </a></li>
      <li><a href="{% url 'petconnect:promocoes' %}"> Promoções Ativas </a></li>
      <li><a href="promocoes-ativas.html"> Avaliações </a></li>
      <li>
        <a href="configuracao.html" class="botao2" button="botao">
          Editar Perfil
        </a>
      </li>
    </ul>
  </div>
</div>

<div id="content">
{% block content_perfil %}
{% endblock %}
</div>
{% endblock %}

templates/petconnect/perfil_usuario.html
{% extends 'petconnect/base.html' %} {% load static %} {% block style %}
<link rel="stylesheet" href="{% static 'css/perfil_usuario.css' %}" />
{% endblock %} {% block nav %} {% endblock %} {% block content %}
<aside>
  <div id="conteudo">
    <div class="circulo"></div>
    <h2>{{ user.first_name }} {{ user.last_name }}</h2>

    <div id="botoes">
      <button><a href="{% url 'petconnect:index' %}">HOME</a></button>
      <button>
        <a href="/src/editar-perfil-usuario.html">EDITAR PERFIL</a>
      </button>
      <button>
        <a href="{% url 'petconnect:cadastro_animal' %}">ANIMAIS CADASTRADOS</a>
      </button>
      <button>
        <a href="{% url 'petconnect:agendar_consulta' %}">AGENDAR CONSULTA</a>
      </button>
    </div>
  </div>
</aside>

<main>
  <div id="conteudo-principal">
    <button>
      <a href="{% url 'petconnect:consultas_agendadas' %}"
        >Consultas Agendadas</a
      >
    </button>
    <button>
      <a href="{% url 'petconnect:consultas_anteriores' %}"
        >Consultas Anteriores</a
      >
    </button>
    <button>
      <a href="{% url 'petconnect:consultas_pendentes' %}"
        >Agendamentos Pendentes</a
      >
    </button>
  </div>
  {% block content_perfil %} {% endblock %}
</main>
{% endblock %} {% block footer %} {% endblock %}